  language: android
  jdk: oraclejdk8
  env:
    global:
      - ANDROID_API_LEVEL=25
      - EMULATOR_API_LEVEL=25
      - ANDROID_BUILD_TOOLS_VERSION=25.0.2
  android:
    components:
      - tools # to get the new `repository-11.xml`
      - tools # see https://github.com/travis-ci/travis-ci/issues/6040#issuecomment-219367943)
      - platform-tools
      - build-tools-$ANDROID_BUILD_TOOLS_VERSION
      - android-$ANDROID_API_LEVEL
      - android-$EMULATOR_API_LEVEL
      - extra
      - extra-android-support

  script:
     -  jdk_switcher use oraclejdk8
     - ./gradlew build
